server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/person
    username: postgres
    password: Gingerbeer.117
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update